# Smart Campus Email Engine Properties
# Use of Google Accounts App Passwords is recommended for Gmail.

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

# Sender account details
mail.from.address=bellapubg007@gmail.com
mail.from.name=Rup Ganesh - Smart Campus
# WARNING: Do NOT place your primary account password here. 
# Go to Google Account > Security > 2-Step Verification > App Passwords, generate an app password, and paste it below.
mail.from.password=irtfyzccjmcayxmx